# Generated by Django 6.0 on 2026-03-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('choice', models.CharField(choices=[('entry', 'Entry level'), ('mid', 'Mid level'), ('expert', 'Experienced')], max_length=10)),
                ('answer', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
